version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: finex-db
    environment:
      POSTGRES_USER: finex
      POSTGRES_PASSWORD: finex123
      POSTGRES_DB: finex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
