version: '3.8'

services:
  nexfy-webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile
    container_name: nexfy-webhook
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - NEXFY_API_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nexfy-network

networks:
  nexfy-network:
    driver: bridge
