version: '3.8'

services:
  wppconnect:
    image: wppconnect/server-cli:latest
    container_name: wppconnect
    restart: always
    ports:
      - "8085:21465"
    environment:
      - SECRET_KEY=THISISMYSECURETOKEN
      - WPPCONNECT_OPTIONS={"autoClose":120000,"waitForLogin":true}
    volumes:
      - wppconnect_data:/home/tokens
    networks:
      - nexfy-network

volumes:
  wppconnect_data:

networks:
  nexfy-network:
    driver: bridge
